### ISSUE TITLE
Plugin doesn't recognize operator name   /\

### ISSUE THREAD

**Issue by Stranger2015** [java-prolog-connectivity/logtalk-intellij#1]
![2019-01-27 18-18-31 binarity-hitalk-1 c users anthony_2 ideaprojects binarity-hitalk-1 - src main java org ltc jpc_p](https://user-images.githubusercontent.com/16267580/52164256-6389c500-26ff-11e9-8ab2-0dfeeeb15967.png)

**Comment by pmoura** [comment]
If you want to write the last two operator between single quotes, you need to write `'/\\'` and `\\/` as `\` starts a character escape sequence.
