### ISSUE TITLE
Error when empty bypass construct occurred

### ISSUE THREAD

**Issue by Stranger2015** [java-prolog-connectivity/logtalk-intellij#11]
steps to reproduce:

1. open logtalk **core.pl** file
2. you will see the following screen:
![изображение](https://user-images.githubusercontent.com/16267580/61168114-48926b00-a551-11e9-8dbe-55ed9ae6dc1a.png)

**Comment by Stranger2015** [comment]
![изображение](https://user-images.githubusercontent.com/16267580/64555096-4d06b480-d345-11e9-821b-669648ef9400.png)

**Comment by sergio-castro** [comment]
fixed (soon to be released)
