### ISSUE TITLE
Error using binary/unary minus.

### ISSUE THREAD

**Issue by Stranger2015** [java-prolog-connectivity/logtalk-intellij#2]
![2019-01-27 18-22-30 binarity-hitalk-1 c users anthony_2 ideaprojects binarity-hitalk-1 - src main java org ltc jpc_p](https://user-images.githubusercontent.com/16267580/52164304-57523780-2700-11e9-8b0f-fe0624468c4a.png)

**Comment by sergio-castro** [comment]
This should be fixed in version 1.0.14. Thanks for reporting.
