### ISSUE TITLE
Possible missing operator definition for protected, private

### ISSUE THREAD

**Issue by Stranger2015** [java-prolog-connectivity/logtalk-intellij#7]
![2019-03-05 17-38-02 jpc_plus c users anthony_2 ideaprojects jpc-teufel - msg lgt - intellij idea](https://user-images.githubusercontent.com/16267580/53813168-11da9180-3f6e-11e9-99a9-6ad8ef6fc428.png)

**Comment by pmoura** [comment]
Logtalk doesn't declare the `public`, `protected`, and `public` atoms as operators. I assume you're using SWI-Prolog, which does declare `public` as operator. For portability, I advised you to avoid using or defining these atoms as operators.

**Comment by sergio-castro** [comment]
I suspected that.
